-- ============================================
-- Zeno ERP - Estrutura do Banco de Dados
-- Banco: PostgreSQL
-- Autor: Zeno / ETEC Martinho Di Ciero
-- Data: 10/10/2025
-- ============================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE public.users (
  company_name TEXT NULL,
  email TEXT NOT NULL,
  cnpj NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  password TEXT NULL,
  name TEXT NULL,
  color TEXT NULL,
  uuid UUID NOT NULL DEFAULT gen_random_uuid(),
  accessibility TEXT NULL,
  features JSONB NOT NULL DEFAULT '{"task": true, "stock": true, "finance": true, "service": true, "calendar": true}'::jsonb,
  logo TEXT NOT NULL DEFAULT 'https://hftlavugxgkarecjykea.supabase.co/storage/v1/object/public/logos/NAO_APAGUE_LOGO_PADRAO/LogoZeno_LogoBrancoSFundo.png'::text,
  CONSTRAINT users_pkey PRIMARY KEY (uuid)
) TABLESPACE pg_default;

CREATE UNIQUE INDEX IF NOT EXISTS users_email_key ON public.users (email);
CREATE INDEX IF NOT EXISTS users_cnpj_idx ON public.users (cnpj);

CREATE TABLE public.calendar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  initial_date DATE NULL,
  uuid UUID NOT NULL,
  end_date DATE NULL,
  title TEXT NULL,
  CONSTRAINT agenda_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_uuid_fkey FOREIGN KEY (uuid) REFERENCES users (uuid) ON UPDATE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  categoria TEXT NOT NULL,
  uuid UUID NOT NULL,
  CONSTRAINT category_pkey PRIMARY KEY (id),
  CONSTRAINT category_uuid_fkey FOREIGN KEY (uuid) REFERENCES users (uuid) ON UPDATE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.employee (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  uuid UUID NOT NULL,
  email TEXT NULL,
  password TEXT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  company_name TEXT NULL,
  cnpj NUMERIC NOT NULL,
  name TEXT NULL,
  color TEXT NULL,
  accessibility TEXT NULL,
  features JSONB NULL,
  logo TEXT NULL,
  CONSTRAINT employee_pkey PRIMARY KEY (id),
  CONSTRAINT employee_uuid_fkey FOREIGN KEY (uuid) REFERENCES users (uuid) ON UPDATE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.finance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  value DOUBLE PRECISION NOT NULL,
  category TEXT NOT NULL,
  payment_method TEXT NOT NULL,
  uuid UUID NOT NULL DEFAULT gen_random_uuid(),
  type_flow TEXT NOT NULL,
  CONSTRAINT finance_pkey PRIMARY KEY (id),
  CONSTRAINT finance_uuid_fkey FOREIGN KEY (uuid) REFERENCES users (uuid) ON UPDATE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.supplier (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  "Number" NUMERIC NOT NULL,
  "Address" TEXT NOT NULL,
  uuid UUID NOT NULL,
  CONSTRAINT supplier_pkey PRIMARY KEY (id),
  CONSTRAINT supplier_uuid_fkey FOREIGN KEY (uuid) REFERENCES users (uuid) ON UPDATE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  description TEXT NULL,
  alert TEXT NOT NULL,
  product_category TEXT NULL,
  minimum_quantity NUMERIC NOT NULL,
  fixed_quantity NUMERIC NOT NULL,
  image TEXT NULL,
  uuid UUID NOT NULL,
  price NUMERIC NOT NULL,
  price1 NUMERIC NOT NULL,
  quantity_of_product NUMERIC NOT NULL,
  "supplierInfo" BIGINT NULL,
  CONSTRAINT product_pkey PRIMARY KEY (id),
  CONSTRAINT product_supplierInfo_fkey FOREIGN KEY ("supplierInfo") REFERENCES supplier (id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT product_uuid_fkey FOREIGN KEY (uuid) REFERENCES users (uuid) ON UPDATE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  status TEXT NOT NULL,
  name_customer TEXT NULL,
  date DATE NOT NULL,
  description TEXT NULL,
  pending_amount NUMERIC NULL,
  name_services TEXT NOT NULL,
  uuid UUID NOT NULL DEFAULT gen_random_uuid(),
  number_customer NUMERIC NULL,
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_uuid_fkey FOREIGN KEY (uuid) REFERENCES users (uuid) ON UPDATE CASCADE
) TABLESPACE pg_default;

CREATE TABLE public.task (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  information TEXT NULL,
  date TEXT NOT NULL,
  uuid UUID NOT NULL,
  status TEXT NOT NULL,
  CONSTRAINT tarefa_pkey PRIMARY KEY (id),
  CONSTRAINT task_uuid_fkey FOREIGN KEY (uuid) REFERENCES users (uuid) ON UPDATE CASCADE
) TABLESPACE pg_default;
